<#
.SYNOPSIS
    ValidSim continuous build pipeline (runs 24/7 via CodeBuddy automation + GitHub Actions).
.DESCRIPTION
    1. Bootstraps a .venv (prefers Python 3.12) and installs requirements.txt.
    2. Runs the pytest suite with JUnit XML output.
    3. Appends a machine-readable line to builds/build-log.csv.
    4. Regenerates "vault/00 - Dashboard/Build Status.md" so the Obsidian vault
       always shows the latest build result (linked from Home as [[Build Status]]).
    Exit codes: 0 = success, 1 = build/test failure, 2 = environment failure.
#>
[CmdletBinding()]
param(
    [int]$ResampleBudget = 500
)

$ErrorActionPreference = "Continue"
$Root      = Split-Path -Parent $PSScriptRoot
$VenvDir   = Join-Path $Root ".venv"
$VenvPy    = Join-Path $VenvDir "Scripts\python.exe"
$BuildsDir = Join-Path $Root "builds"
$LogCsv    = Join-Path $BuildsDir "build-log.csv"
$JUnit     = Join-Path $BuildsDir "junit.xml"
$StatusMd  = Join-Path $Root "vault\00 - Dashboard\Build Status.md"
$LastLog   = Join-Path $BuildsDir "last-build-output.txt"

if (-not (Test-Path $BuildsDir)) { New-Item -ItemType Directory -Path $BuildsDir | Out-Null }
Set-Location $Root

$started = Get-Date
$ok = $false
$stage = "env"
$summary = ""

# ---- 1. Bootstrap venv (prefer 3.12 for wheel compatibility) --------------
if (-not (Test-Path $VenvPy)) {
    $booted = $false
    foreach ($cand in @(@("py", "-3.12"), @("python"), @("python3"))) {
        try {
            $probe = & $cand[0] @($cand[1..($cand.Length - 1)] + @("-c", "import sys; sys.exit(0 if sys.version_info >= (3,10) else 1)")) 2>$null
            if ($LASTEXITCODE -eq 0) {
                & $cand[0] @($cand[1..($cand.Length - 1)] + @("-m", "venv", $VenvDir)) *> $null
                if ((Test-Path $VenvPy)) { $booted = $true; break }
            }
        } catch { }
    }
    if (-not $booted) {
        "FATAL: no usable Python interpreter (>=3.10) found" | Out-File -FilePath $LastLog -Encoding utf8
        Write-Host "BUILD FAILED (env): no usable Python interpreter" -ForegroundColor Red
        exit 2
    }
}

# ---- 2. Install dependencies ----------------------------------------------
$stage = "install"
& $VenvPy -m pip install --quiet --disable-pip-version-check --upgrade pip *> $null
& $VenvPy -m pip install --quiet --disable-pip-version-check -r (Join-Path $Root "requirements.txt") *>&1 |
    Out-File -FilePath $LastLog -Encoding utf8
if ($LASTEXITCODE -eq 0) { $ok = $true } else { $summary = "pip install failed (see builds/last-build-output.txt)" }

# ---- 3. Run tests -----------------------------------------------------------
if ($ok) {
    $stage = "test"
    $testOut = & $VenvPy -m pytest tests --junitxml $JUnit 2>&1
    $testExit = $LASTEXITCODE
    $testOut | Out-File -FilePath $LastLog -Append -Encoding utf8
    $tailLine = ($testOut | Where-Object { $_ -match "(passed|failed|error)" } | Select-Object -Last 1)
    if ($null -eq $tailLine) { $tailLine = "" }
    $summary = ($tailLine -replace "\s+", " ").Trim()
    if ($testExit -eq 0) { $ok = $true } else { $ok = $false }
}

$duration = [math]::Round(((Get-Date) - $started).TotalSeconds, 1)
$result = if ($ok) { "PASS" } else { "FAIL" }

# ---- 4. Append build log ----------------------------------------------------
if (-not (Test-Path $LogCsv)) {
    "timestamp_utc,result,stage,duration_s,summary" | Out-File -FilePath $LogCsv -Encoding utf8
}
$esc = $summary -replace '"', '""'
"{0},{1},{2},{3},`"{4}`"" -f $started.ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss"), $result, $stage, $duration, $esc |
    Out-File -FilePath $LogCsv -Append -Encoding utf8

# ---- 5. Regenerate the vault Build Status note ------------------------------
if (Test-Path $StatusMd) { Remove-Item $StatusMd -Force }
$recent = @()
if (Test-Path $LogCsv) {
    $recent = Import-Csv -Path $LogCsv | Select-Object -Last 15
}
$rows = ($recent | ForEach-Object {
    $icon = if ($_.result -eq "PASS") { "PASS" } else { "FAIL" }
    "| {0} UTC | {1} | {2} | {3}s | {4} |" -f $_.timestamp_utc, $icon, $_.stage, $_.duration_s, $_.summary
}) -join [Environment]::NewLine

$passCount  = @($recent | Where-Object { $_.result -eq "PASS" }).Count
$totalCount = @($recent).Count
$rate = if ($totalCount -gt 0) { [math]::Round(100.0 * $passCount / $totalCount, 1) } else { 0 }

@"
---
tags: [build, automation, dashboard]
status: active
created: 2026-09-18
area: dashboard
auto_generated: true
---

# Build Status

> [!info] Auto-generated by ``scripts/build.ps1``
> Runs 24/7 via CodeBuddy automation (hourly) and on every push via GitHub Actions (``.github/workflows/ci.yml``). Do not edit manually.

## Latest Run

| Field | Value |
|---|---|
| **Result** | $result |
| **Stage** | $stage |
| **Time (UTC)** | $($started.ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss")) |
| **Duration** | ${duration}s |
| **Summary** | $summary |

**Pass rate (last $totalCount runs): $rate%**

## Recent Builds

| Time (UTC) | Result | Stage | Duration | Summary |
|---|---|---|---|---|
$rows

## Links

[[Home]] | [[8-Week Sprint Plan]] | [[MVP Success Metrics]]
"@ | Out-File -FilePath $StatusMd -Encoding utf8

Write-Host "BUILD $result ($stage, ${duration}s) - $summary" -ForegroundColor $(if ($ok) { "Green" } else { "Red" })
exit $(if ($ok) { 0 } else { 1 })
